[package]
name = "ilya_pimenov_study_crate1"
license = "MIT OR Apache-2.0"
version = "0.1.0"
description = "A sample study cargo by Ilya Pimenov"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
